package fiap.sd.udp.chat;

public enum Comandos {
	ACESSAR,
	REGISTRAR,
	REQUISITAR_NOME_USUARIO,
	ENVIAR_NOME_USUARIO,
	USUARIO_REGISTRADO_SUCESSO,
	EXIBE_MSG,
	SUCESSO,
	ESCOLHE_MENU,
	MENU_INVALIDO,
	LISTAR_SALA_SUCESSO
}
