package fiap.sd.udp.chat;

public enum Commands {
	NOTIFICATION,
	ACCESS,
	REQUEST_USER_NAME,
	SEND_USER_NAME,
	MENU_APP,
	MENU_ROOM,
	INVALID_COMMAND,
	REQUEST_CREATE_ROOM,
	SEND_CREATE_ROOM,
	REQUEST_JOIN_ROOM,
	SEND_JOIN_ROOM	
}
